// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxpfpSyNT_U5YoGYjfVQxg0W6_Iiy3ZPs',
    appId: '1:803017632256:web:5c06a071aa493fb5b746e5',
    messagingSenderId: '803017632256',
    projectId: 'sampleproject-6db4c',
    authDomain: 'sampleproject-6db4c.firebaseapp.com',
    storageBucket: 'sampleproject-6db4c.firebasestorage.app',
    measurementId: 'G-C4F6VL7V8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGUtq8_KA3yCKJyI1JxcLkgi-zH4lXz6k',
    appId: '1:803017632256:android:5f57cb40d80a4e90b746e5',
    messagingSenderId: '803017632256',
    projectId: 'sampleproject-6db4c',
    storageBucket: 'sampleproject-6db4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMXFLLLWJgUOfAOZLHUPC78PeM6NvTk38',
    appId: '1:803017632256:ios:ed0667a3817af65bb746e5',
    messagingSenderId: '803017632256',
    projectId: 'sampleproject-6db4c',
    storageBucket: 'sampleproject-6db4c.firebasestorage.app',
    iosBundleId: 'com.example.mobapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMXFLLLWJgUOfAOZLHUPC78PeM6NvTk38',
    appId: '1:803017632256:ios:ed0667a3817af65bb746e5',
    messagingSenderId: '803017632256',
    projectId: 'sampleproject-6db4c',
    storageBucket: 'sampleproject-6db4c.firebasestorage.app',
    iosBundleId: 'com.example.mobapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxpfpSyNT_U5YoGYjfVQxg0W6_Iiy3ZPs',
    appId: '1:803017632256:web:ddc4ab007ca59290b746e5',
    messagingSenderId: '803017632256',
    projectId: 'sampleproject-6db4c',
    authDomain: 'sampleproject-6db4c.firebaseapp.com',
    storageBucket: 'sampleproject-6db4c.firebasestorage.app',
    measurementId: 'G-R69HJGJ0GX',
  );

}